import Head from "next/head";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import PortfolioPageBody from "@/Components/PortfolioPageBody";
import Script from "next/script";

function PortfolioPage() {
    return (

        <>
            <Head>
                <title>Sravan Karuturi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-white px-0'>

                <Navbar />

                <PortfolioPageBody />

                <Footer />

                <Script src="../node_modules/flowbite/dist/flowbite.min.js" />

            </main>
        </>

    );
}

export default PortfolioPage;