import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub, AiFillMail} from 'react-icons/ai';
import Image from 'next/image';
import profile from '../public/profile.png'
import Footer from '../Components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sravan Karuturi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-0'>
        <section className='min-h-screen bg-teal-500 '>
          <nav className='py-6 mb-10 flex justify-between bg-slate-800'>
            <h1 className='text-xl font-serif text-white mx-10'> Sravan Karuturi </h1>
            <ul className='flex items-center mx-10'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl text-white' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <div className="relative ">
              <div className='py-10'>
                <Image className='overflow-clip rounded-full w-80 h-80 flex mx-auto' src={profile} />
              </div>
            </div>
            <h2 className='text-5xl py-2 text-white font-semibold'>SRAVAN KARUTURI</h2>
            <h3 className='text-2xl py-2 text-white font-medium'>Developer</h3>
            <p className='text-md py-5 leading-8 text-white'>Game Developer and Full Stack Developer</p>
          </div>

          

          
        </section>

        <section>
          
        </section>

        {/* Next Section */}

        <section>
          
          <div>
            <h3> Portfolio </h3>
          </div>

        </section>

        <Footer />

      </main>
    </>
  )
}
