import Head from 'next/head';

import Navbar from '@/Components/Navbar';
import Intro from '@/Components/Intro'
import HomescreenPortfolio from '@/Components/HomescreenPortfolio';
import Footer from '@/Components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sravan Karuturi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-0'>
        
        <Navbar />
        <Intro />
        <HomescreenPortfolio />
        <Footer />

      </main>
    </>
  )
}
